spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-ui

info:
  project:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    type: core
    artifact-id: @project.artifactId@

server:
  port: 8081